apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: demo-ops
  app: demo
spec:
  selector:
    matchLabels:
      app: demo
  replicas: 3
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - image: demo-app:v1
        name: demo-app
        ports:
        - containerPort: 8080
        - hostPort: 8000
        resources:
            limits:
              memory: "500Mi"
              cpu: "1000m"      
            requests:
              memory: "300Mi"
              cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/v1/status
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5